config/routes.rb
Rails.application.routes.draw do
  root to: "employees#index"

  resources :employees, except: %i[show destroy]
  delete "employees/:id", to: "employees#destroy", as: :destroy_employee

  resources :employees, only: [] do
    member do
      patch :set_table
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true
  validates :unit, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[edit update destroy]
  before_action :all_employees, only: %i[index update_table set_table]

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.create(employee_params)
    if @employee.save
      redirect_to employees_path
    end
  end

  def edit
  end

  def update_table(employee)
    if @employees.count > 5
      employee.update(table: rand(1..((@employees.count.to_f / 5).ceil)))
    else
      employee.update(table: 1)
    end
  end

  def set_table
    @employees.each do |employee|
      update_table(employee)
    end
    redirect_to employees_path
  end

  def update
    @employee.update(employee_params)
    redirect_to employees_path
  end

  def destroy
    @employee.destroy!
    redirect_to employees_path, status: :see_other
  end

  private

  def all_employees
    @employees = Employee.all
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:name, :unit)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/edit.html.erb
<div class="container">
  <div class="formulaire">
    <h2>Edit employee</h2>
      <%= simple_form_for [@employee] do |f| %>
        <%= f.input :name %>
        <%= f.input :unit %>
        <%= f.button :submit, class: "button" %>
      <% end %>
  </div>
</div>

app/views/employees/index.html.erb
<div class="container-2">
  <div class="container-2">
    <h1>Tables</h1>
    <% if @employees.count.positive? %>
      <%= button_to "set tables", set_table_employee_path(@employees), method: :patch, class: "btn-archive mt-3" %>
    <% end %>
    <div class="index_candidates">
      <% tables = [] %>
      <% @employees.each do |employee| %>
        <% tables << employee.table if tables.exclude?(employee.table) && employee.table != 0 %>
      <% end %>
      <% tables.each do |number| %>
        <div class="card_candidate">
          <h2><%= "Table #{number}" %></h2>
          <br>
          <% @employees.where(table: number).each do |employee| %>
            <h3><%= employee.name %></h3>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container-2">
    <h1>Employees</h1>
    <%= link_to "add employee", new_employee_path, class: "btn-archive mt-3" %>
    <div class="index_candidates">
      <% @employees.each do |employee| %>
        <div class="card_candidate">
          <h2><%= employee.name %></h2>
          <h3><%= employee.unit %></h3>
          <%= link_to 'delete', destroy_employee_path(employee), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn-details mt-5" %>
          <%= link_to 'edit', edit_employee_path(employee), class: "btn-details mt-5" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="container">
  <div class="formulaire">
    <h2>New employee</h2>
      <%= simple_form_for [@employee] do |f| %>
        <%= f.input :name %>
        <%= f.input :unit %>
        <%= f.button :submit, class: "button" %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataGuard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>